//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 12:39:50 AM IST 
//


package com.chubbindia.employees;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmpDetails" type="{http://chubbindia.com/employees}EmpDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "empDetails"
})
@XmlRootElement(name = "GetEmployeeDetailsResponse")
public class GetEmployeeDetailsResponse {

    @XmlElement(name = "EmpDetails", required = true)
    protected EmpDetails empDetails;

    /**
     * Gets the value of the empDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EmpDetails }
     *     
     */
    public EmpDetails getEmpDetails() {
        return empDetails;
    }

    /**
     * Sets the value of the empDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmpDetails }
     *     
     */
    public void setEmpDetails(EmpDetails value) {
        this.empDetails = value;
    }

}
